name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # buildozerが必要とする最小限のシステム依存関係をインストール
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake \
          libffi-dev \
          libssl-dev

    # Pythonの依存関係をインストール
    - name: Install Python dependencies
      run: |
        pip install "cython<3.0" # buildozerとの互換性のため
        pip install buildozer

    # buildozer.specファイルがリポジトリにコミットされていることを前提とする
    # 動的な書き換えは行わない

    # buildozerを実行してAPKをビルド
    - name: Build APK with Buildozer
      run: |
        buildozer android debug --verbose

    # ビルドされたAPKをアップロード
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk # buildozerはbin/ディレクトリにAPKを生成