name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # buildozerと、ライブラリのコンパイルに必要な最小限のツールのみをインストール
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake \
          libffi-dev \
          libssl-dev

    # Pythonの依存関係をインストール
    - name: Install Python dependencies
      run: |
        pip install "cython<3.0"
        pip install buildozer

    # buildozerを実行。SDK/NDKのダウンロード、設定、ライセンス同意、ビルドの全てを自動で行う
    - name: Build APK with Buildozer
      env:
        # この一行が、対話的なライセンス同意プロンプトをスキップさせる
        ACCEPT_EULA: "Y"
      run: |
        buildozer android debug --verbose

    # 完成したAPKをアーティファクトとしてアップロード
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk